services:
  traefik:
    container_name: traefik
    hostname: traefik
    image: zzci/traefik
    restart: always
    ports:
      - 0.0.0.0:80:80
      - 0.0.0.0:443:443/tcp
    networks:
      traefik:
        ipv4_address: ${TRAEFIK_IPV4:-172.18.0.2}
    volumes:
      - ./data:/data
      - ./services:/services
    command:
      - --configFile=/data/traefik.yml
      - --certificatesresolvers.default.acme.email=${ACME_EMAIL:-admin@example.com}
      - --certificatesresolvers.dns.acme.email=${ACME_EMAIL:-admin@example.com}
    environment:
      LEGO_DISABLE_CNAME_SUPPORT: ${ACME_DISABLE_CNAME:-true}
      HTTPREQ_ENDPOINT: https://api.dnsall.com
      HTTPREQ_USERNAME: xxx
      HTTPREQ_PASSWORD: xxx

networks:
  traefik:
    name: ${TRAEFIK_NETWORK:-traefik}
    ipam:
      config:
        - subnet: ${TRAEFIK_SUBNET:-172.18.0.0/16}
