global:
  checkNewVersion: false
  sendAnonymousUsage: false

api:
  dashboard: true

log:
  level: error
  filePath: /data/logs/proxy.log

accessLog:
  filePath: /data/logs/access.log

entryPoints:
  http:
    address: :80
    http:
      redirections:
        entryPoint:
          to: https
          scheme: https
  https:
    address: :443
    # Don't trust X-Forwarded-* from downstream, only trust from specific IPs
    forwardedHeaders:
      insecure: false
      # trustedIPs:
      #   - 127.0.0.1/32
      #   - 10.0.0.0/8

experimental:
  localPlugins:
    oidc:
      moduleName: github.com/sevensolutions/traefik-oidc-auth
    realIp:
      moduleName: github.com/Paxxs/traefik-get-real-ip

certificatesResolvers:
  default:
    acme:
      httpChallenge:
        entryPoint: http
      storage: /data/ssl/default.json
  dns:
    acme:
      dnsChallenge:
        provider: acme-dns
        resolvers:
          - 1.1.1.1:53
          - 8.8.8.8:53
      storage: /data/ssl/dns.json

providers:
  file:
    directory: /services
    watch: true
  # http:
  #   endpoint: https://demo.io/config
  #   pollInterval: 10s
  #   pollTimeout: 60s
  #   tls:
  #     cert: /data/ssl/client.crt
  #     key: /data/ssl/client.key
